### PR TITLE
Update get init frames

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/12)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/include/FrameSkipper.h, line 131 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGc7HttmGwgpKQlLk1:-KrGc7HttmGwgpKQlLk2:b-k4hw1b) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/include/FrameSkipper.h#L131)):*
> ```objc
> 
> 
>         int GetAvailableInitializationFrameCount() const;
> ```

Please add a comment block.

---

*[detection/api/include/MPFVideoCapture.h, line 114 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGbXfAX8Ei08Y0AJim:-KrGbXfAX8Ei08Y0AJin:b-w8gp4z) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/include/MPFVideoCapture.h#L114)):*
> ```objc
>          * @param numberOfRequestedFrames
>          * @return Vector that contains between 0 and numberOfRequestedFrames frames
>          */
> ```

Add comma:

"beginning of segment, skipping frameInterval frames."

---

*[detection/api/src/MPFVideoCapture.cpp, line 269 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGeJ2T8Y-_sin7YZ9C:-KrGdWh6ueAjuTEHGHjO:b-a0svgo) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/src/MPFVideoCapture.cpp#L269)):*
> ```cpp
> 
>     std::vector<cv::Mat> MPFVideoCapture::GetInitializationFramesIfAvailable(int numberOfRequestedFrames) {
>         int initFramesAvailable = frameSkipper_.GetAvailableInitializationFrameCount();
> ```

`GetAvailableInitializationFrameCount()` assumes that you're at startFrame_. Below you're setting `initialFramePos` to the current frame position. What if this is called when we're not at the startFrame_?

In that case it seems that it will return 0 or more frames before the current position, but these won't necessarily be the frames before the start of the segment (and the number of frames returned is not based on your current position).

Shouldn't `initialFramePos`always be equal to startFrame_? My thought is that this function should behave the same way no matter what the current frame position is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12)*

**Comment by jrobble** [comment]
P.S. I think you have to merge with @clnowacki's recent protobuf changes.

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/src/MPFVideoCapture.cpp, line 269 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGeJ2T8Y-_sin7YZ9C:-KrGh3coQy7q5yKieckE:bftknwg) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/src/MPFVideoCapture.cpp#L269)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`GetAvailableInitializationFrameCount()` assumes that you're at startFrame_. Below you're setting `initialFramePos` to the current frame position. What if this is called when we're not at the startFrame_?

In that case it seems that it will return 0 or more frames before the current position, but these won't necessarily be the frames before the start of the segment (and the number of frames returned is not based on your current position).

Shouldn't `initialFramePos`always be equal to startFrame_? My thought is that this function should behave the same way no matter what the current frame position is.
</blockquote></details>

Say startFrame = 10, frameInterval = 5, the current position is 20, and you call GetInitializationFramesIfAvailable(2). Which frames should be returned?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12)*

**Comment by jrobble** [comment]
*[detection/api/src/MPFVideoCapture.cpp, line 269 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGeJ2T8Y-_sin7YZ9C:-KrGm_syqZ5C_9FEC8Aw:b-20rqe8) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/src/MPFVideoCapture.cpp#L269)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Say startFrame = 10, frameInterval = 5, the current position is 20, and you call GetInitializationFramesIfAvailable(2). Which frames should be returned?
</blockquote></details>

I think the term "initialization" implies "before the start of the segment", so in that case frames 0 and 5 should be returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12)*

**Comment by brosenberg42** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/include/FrameSkipper.h, line 131 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGc7HttmGwgpKQlLk1:-KrGrn1c30Tr1ytmdClH:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/include/FrameSkipper.h#L131)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a comment block.
</blockquote></details>

Done.

---

*[detection/api/include/MPFVideoCapture.h, line 114 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGbXfAX8Ei08Y0AJim:-KrGroo8tIsSKVtOOI0X:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/include/MPFVideoCapture.h#L114)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add comma:

"beginning of segment, skipping frameInterval frames."
</blockquote></details>

Done.

---

*[detection/api/src/MPFVideoCapture.cpp, line 269 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12#-KrGeJ2T8Y-_sin7YZ9C:-KrGrzkvefKAoTVXn2Ee:by8vasa) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6101d2771680cb5354a881d93a71734240b82ad0/detection/api/src/MPFVideoCapture.cpp#L269)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think the term "initialization" implies "before the start of the segment", so in that case frames 0 and 5 should be returned.
</blockquote></details>

That is what it does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/12)*

**Pull request merged**
