### PR TITLE
Add support for ROTATION_THRESHOLD and ROTATION_FILL_COLOR

### PR DESCRIPTION
**Pull request by brosenberg42**
Resolves https://github.com/openmpf/openmpf/issues/1194
Resolves https://github.com/openmpf/openmpf/issues/1196

Associated PRs:
- https://github.com/openmpf/openmpf/pull/1195
- https://github.com/openmpf/openmpf-components/pull/203
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/93
- https://github.com/openmpf/openmpf-python-component-sdk/pull/33

This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)

### CODE REVIEW

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[detection/api/src/detectionComponentUtils.cpp, line 127 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLieCth2z1HoqfYc912:-MLieCti3cNp-6f5HWsj:b-e8fd04) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6adb3a48a7a9fc4da48b70f047a4f4c7388bb440/detection/api/src/detectionComponentUtils.cpp#L127)):*
> ```cpp
> 
>     bool RotationAnglesEqual(double a1, double a2, double epsilon) {
>         a1 = NormalizeAngle(a1);
> ```

I'm not used to redefining function parameters like this. It seems like bad practice, although functionally it's fine in this case. CLion doesn't even complain.
___
*[detection/api/src/detectionComponentUtils.cpp, line 133 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLie6224E5Zy4arfsM0:-MLie6238PpTx2aH64Ok:bm01ir5) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6adb3a48a7a9fc4da48b70f047a4f4c7388bb440/detection/api/src/detectionComponentUtils.cpp#L133)):*
> ```cpp
>         }
>         else {
>             double a1_dist = std::min(a1, std::abs(360 - a1));
> ```

Nice catch with the rollover case :thumbsup:

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[detection/api/test/test_detection_api.cpp, line 1316 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLj-KpND6Un5TmeiLxn:-MLj-KpP3qPnEzZoN03S:b-fk92ch) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6adb3a48a7a9fc4da48b70f047a4f4c7388bb440/detection/api/test/test_detection_api.cpp#L1316)):*
> ```cpp
> 
>         auto img = MPFImageReader(job).GetImage();
>         ASSERT_NE(original_img.size(), img.size());
> ```

Here you check image size, but in the Python SDK you check pixel values:

```
        job.job_properties['ROTATION_THRESHOLD'] = '9.99'
        img = mpf_util.ImageReader(job).get_image()
        self.assertFalse(np.all(original_img == img))
```

**Review by jrobble — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

**Review by jrobble — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLjDCaYCR9CJa-e9jf9:-MLjDCaYCR9CJa-e9jfA:b-b1z6pi) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6adb3a48a7a9fc4da48b70f047a4f4c7388bb440/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L114)):*
> ```cpp
>         auto fillColorName = DetectionComponentUtils::GetProperty(
>                 props, "ROTATION_FILL_COLOR", "BLACK");
>         if (fillColorName == "BLACK") {
> ```

I got this error due to using lowercase:

```
   "errors": [
      {
         "mediaId": 11,
         "details": [
            {
               "source": "TESSERACTOCR",
               "code": "INVALID_PROPERTY",
               "message": "An exception occurred while trying to get detections from image: Expected the \"ROTATION_FILL_COLOR\" property to be either \"BLACK\" or \"WHITE\", but it was set to \"black\"."
            }
         ]
      }
   ],
```

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[detection/api/src/detectionComponentUtils.cpp, line 127 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLieCth2z1HoqfYc912:-MLmqKYhBt2DhypR-Tf4:buq6p5r) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6adb3a48a7a9fc4da48b70f047a4f4c7388bb440/detection/api/src/detectionComponentUtils.cpp#L127)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm not used to redefining function parameters like this. It seems like bad practice, although functionally it's fine in this case. CLion doesn't even complain.
</blockquote></details>

I normally don't, but in this case I felt it was better than the alternative.
___
*[detection/api/test/test_detection_api.cpp, line 1316 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLj-KpND6Un5TmeiLxn:-MLmf9rl5j7CjvQElrb-:b-kh9hzw) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6adb3a48a7a9fc4da48b70f047a4f4c7388bb440/detection/api/test/test_detection_api.cpp#L1316)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Here you check image size, but in the Python SDK you check pixel values:

```
        job.job_properties['ROTATION_THRESHOLD'] = '9.99'
        img = mpf_util.ImageReader(job).get_image()
        self.assertFalse(np.all(original_img == img))
```
</blockquote></details>

When you try to compare images with different sizes, OpenCV throws an exception. I also just noticed that I get a deprecation warning for `self.assertFalse(np.all(original_img == img))`: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.". I am changing those `np.array_equal`

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 115 at r3](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/93#-MLnejGLBwjOBHrfnFu5:-MLnejGLBwjOBHrfnFu6:b-neiyzy) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d7c4948c389deae2018931df972d1182b7d5a0dc/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L115)):*
> ```cpp
> 
>     cv::Scalar GetFillColor(const Properties &props) {
>         auto fillColorName = GetProperty(props, "ROTATION_FILL_COLOR", "BLACK");
> ```

Other places in this file still have the `DetectionComponentUtils::` prefix.

**Pull request merged**
