### PR TITLE
reorganized for batch and added streaming API files

### PR DESCRIPTION
**Pull request by clnowacki**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/5)

### CODE REVIEW

**Comment by jrobble** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 53 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp262_rJjNcm0MtJbQp:-Kp262_rJjNcm0MtJbQq:b5lwc3r) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L53)):*
> ```objc
>                 const size_t buffer_size,
>                 std::string &error_string);
>     void Close(std::string &error_string);
> ```

Should the above functions also return a 0 or 1 to indicate success / failure? This is in addition to using the error_string.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-Kp25Rcp3Wql3PVyXg7t:b2yyuaa) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
> ```objc
>     void Close(std::string &error_string);
> 
>     // The frame byte size is supplied along with the offset so that
> ```

Is the offset the same as the frame Id?

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 1 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25YCCwcUbHvpZ-V6A:-Kp25YCCwcUbHvpZ-V6B:b8hmjxv) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L1)):*
> ```cpp
> #include <fcntl.h>
> ```

Please add the header comment blocks.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 75 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27MB4d3hnr3XcVOC2:-Kp27MB4d3hnr3XcVOC3:b-lv0pcy) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L75)):*
> ```cpp
>     }
>     buffer_name_ = frame_store_name;
>     buffer_byte_size_ = buffer_size;
> ```

Maybe we should have a constructor that takes the frame_store_name and buffer_size instead of setting them here.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 105 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27UIDaTAYbMrkIW9v:-Kp27UIDaTAYbMrkIW9w:b-lv0pcy) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L105)):*
> ```cpp
>     }
>     buffer_name_ = frame_store_name;
>     buffer_byte_size_ = buffer_size;
> ```

Maybe we should have a constructor that takes the frame_store_name and buffer_size instead of setting them here.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 118 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27s8aG89cDb2HaObH:-Kp27s8aG89cDb2HaObI:b8q6jr8) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L118)):*
> ```cpp
>     }
> 
>     close(storage_handle_);
> ```

Does `close()` also set the value of storage_handle? If not, we might want to set it to some default / invalid value.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 126 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp28QGCP2iXmhk41h8B:-Kp28QGDBm0MAmmHJybt:bgxh3ma) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L126)):*
> ```cpp
>                                         uint64_t frame_byte_size,
>                                         string &error_string) {
>     if ( (offset + frame_byte_size) > buffer_byte_size_ ) {
> ```

To be safe, we should also return NULL of the frame store has been closed or not configured properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-:-Kp28kuGXhVnkS1rnRmA:bnfp4nl)*

**Comment by clnowacki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 53 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp262_rJjNcm0MtJbQp:-KpFfY-Gj76xKwrRodKn:b5in87q) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L53)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should the above functions also return a 0 or 1 to indicate success / failure? This is in addition to using the error_string.
</blockquote></details>

Yes that makes sense.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KpFfdB-DR973RYvfaMy:b-bnfxmt) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is the offset the same as the frame Id?
</blockquote></details>

The offset is the number of bytes from the start of the file to the start of the frame in the buffer. The sum of the frame buffer start address and the offset gives you the start of the frame in the frame buffer. 

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 75 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27MB4d3hnr3XcVOC2:-KpFgMWboTQbqsZmAh5e:b-r6lp0x) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L75)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Maybe we should have a constructor that takes the frame_store_name and buffer_size instead of setting them here.
</blockquote></details>

The FrameReader needs to be default constructed, since it is being loaded as a plugin, so the FrameStore it contains also needs to be default constructed. I didn't see any use for a constructor that took those arguments, but I guess there could be some use in other situations.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 105 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27UIDaTAYbMrkIW9v:-KpFhIY0XORxB9VXpVYf:b-sphny9) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L105)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Maybe we should have a constructor that takes the frame_store_name and buffer_size instead of setting them here.
</blockquote></details>

The comment above for the FrameReader also applies here.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 118 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27s8aG89cDb2HaObH:-KpFhTV7-89iwNKPsf1D:b3bt6q9) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L118)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Does `close()` also set the value of storage_handle? If not, we might want to set it to some default / invalid value.
</blockquote></details>

A good idea, yes.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 126 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp28QGCP2iXmhk41h8B:-KpFhXg6o9Aqa1ChEo_G:bb77ufg) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L126)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

To be safe, we should also return NULL of the frame store has been closed or not configured properly.
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by clnowacki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 1 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25YCCwcUbHvpZ-V6A:-KpFmWgebUXm1ScxioxR:b-xwpt6y) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add the header comment blocks.
</blockquote></details>

Wil do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by jrobble** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[detection/api/CMakeLists.txt, line 33 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-KpFyR3NPQCzTuaciwFV:-KpFyR3NPQCzTuaciwFW:bbf94pu) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/CMakeLists.txt#L33)):*
> ```CMake
> set(CMAKE_CXX_STANDARD 11)
> 
> find_package(OpenCV 3.1 EXACT REQUIRED PATHS /opt/opencv-3.1.0
> ```

Just a friendly reminder that we should update this to 3.2 before this code lands.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KpFtRsWpV9n3AdsPJn_:b-2aumhs) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The offset is the number of bytes from the start of the file to the start of the frame in the buffer. The sum of the frame buffer start address and the offset gives you the start of the frame in the frame buffer. 
</blockquote></details>

Ok. I was thinking that depending on how the class that calls this function works, it may be cleaner to just pass the frame Id and do the (frame_index * frame_byte_size) calculation internally; however, that assumes a constant frame byte size, which may not be the case when the camera increases or decreases the resolution. 

With that in mind, should the frame byte size be something that's passed in the MPFFrameReadyMessage?

How would we handle the case where the frame reader process dies and is restarted? The offset seems like it's state that will be lost when the process dies. When the frame reader process is restarted, how will it know the offset to write the next frame?

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 75 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp27MB4d3hnr3XcVOC2:-KpFyI-8hhFud-QhCngI:b-bz7yzg) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L75)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The FrameReader needs to be default constructed, since it is being loaded as a plugin, so the FrameStore it contains also needs to be default constructed. I didn't see any use for a constructor that took those arguments, but I guess there could be some use in other situations.
</blockquote></details>

Ok, the default constructor makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 53 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp262_rJjNcm0MtJbQp:-KpFoJ0iqCXyLEpIGXdE:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L53)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Yes that makes sense.
</blockquote></details>

Done.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KpG7-bLb7TrcQ-pi9zA:blucp4s) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Ok. I was thinking that depending on how the class that calls this function works, it may be cleaner to just pass the frame Id and do the (frame_index * frame_byte_size) calculation internally; however, that assumes a constant frame byte size, which may not be the case when the camera increases or decreases the resolution. 

With that in mind, should the frame byte size be something that's passed in the MPFFrameReadyMessage?

How would we handle the case where the frame reader process dies and is restarted? The offset seems like it's state that will be lost when the process dies. When the frame reader process is restarted, how will it know the offset to write the next frame?
</blockquote></details>

The frame_index*frame_byte_size calculation only works if we are writing frames sequentially. We do that for the first N segments, but once the frame store has been filled, we then start scattering the frames, based on the ReleaseFrame messages returned from the components and the VideoWriter. These messages don't contain a frame_index but an offset instead. The frame_index is monotonically increasing for the life of the job; the offsets are reused as they become available. After the frame store has been completely filled once, the association between frame index and the offset in the buffer is broken.

For now, we (I) have been assuming that the frame byte size is constant. The logic to ensure that we don't overwrite frames that are still in use would be much more complicated if every frame could be a different size. We would then need an actual allocator, keeping track of a free list that can merge adjacent free blocks if necessary, and dealing with issues like fragmentation. I would say that we should leave that for a future enhancement.

If the FrameReader dies, then any unacknowledged ReleaseFrame messages would still be available in the queue. There are other issues bigger than this if the FrameReader dies, such as how does it know that it shouldn't just start storing frames at the beginning of the buffer? There is much state that would be lost if the FrameReader dies, like what the current frame index and segment index are, for example. I can see a soft recovery if a detection process or video writer dies, but a good recovery from a frame reader crash would be much harder.

---

*[detection/api/src/streaming/MPFFrameStore.cpp, line 1 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25YCCwcUbHvpZ-V6A:-KpFoRy2GdU6rtElaDwu:b3oh8n) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/src/streaming/MPFFrameStore.cpp#L1)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Wil do
</blockquote></details>


Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KpGGv_HsTN-SH3eKVBm:boo88bf) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
> For now, we (I) have been assuming that the frame byte size is constant. The logic to ensure that we don't overwrite frames that are still in use would be much more complicated if every frame could be a different size.

I understand the difficulty, but does the current approach support changes in resolution? Since that's a primary use case, I don't think we can push it off until later.

> There are other issues bigger than this if the FrameReader dies, such as how does it know that it shouldn't just start storing frames at the beginning of the buffer? There is much state that would be lost if the FrameReader dies, like what the current frame index and segment index are, for example.

Yeah, that's what I was thinking. I'm not saying we have to do this now, but would it make sense to write that index information to the memory mapped file when a frame is written?

Supporting a soft recovery of the frame reader certainly warrants its own issue; I'd like to make sure we're considering that now so we don't design ourselves into a corner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KpGLSRP51m5nMWlhnJk:b7hut6h) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> For now, we (I) have been assuming that the frame byte size is constant. The logic to ensure that we don't overwrite frames that are still in use would be much more complicated if every frame could be a different size.

I understand the difficulty, but does the current approach support changes in resolution? Since that's a primary use case, I don't think we can push it off until later.

> There are other issues bigger than this if the FrameReader dies, such as how does it know that it shouldn't just start storing frames at the beginning of the buffer? There is much state that would be lost if the FrameReader dies, like what the current frame index and segment index are, for example.

Yeah, that's what I was thinking. I'm not saying we have to do this now, but would it make sense to write that index information to the memory mapped file when a frame is written?

Supporting a soft recovery of the frame reader certainly warrants its own issue; I'd like to make sure we're considering that now so we don't design ourselves into a corner.
</blockquote></details>

The current frame storage approach would support changes in frame size where the frame size is smaller than the size of the original frame. It does not support frame sizes that are larger than the original frame size. Our current crop of detection components can't handle a change in frame size within a segment that is being processed, but we could certainly handle it on a segment boundary with no changes. Changing size from frame to frame would require more changes to the tracking logic itself.

We could reserve space at the start or end of the file and write the current frame reader state there after each frame is read. If we did that we might still have a problem, depending on at what point in its processing it crashed, but I think the problem would be limited. Probably better than nothing, I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by jrobble** [comment]
*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KpGn1cX7iVSqqjKHsor:b-s9t50m) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
> The current frame storage approach would support changes in frame size where the frame size is smaller than the size of the original frame. It does not support frame sizes that are larger than the original frame size. Our current crop of detection components can't handle a change in frame size within a segment that is being processed, but we could certainly handle it on a segment boundary with no changes. Changing size from frame to frame would require more changes to the tracking logic itself.

I think it's reasonable if we require the user to specify the maximum frame size (width and height) when creating the job so we know the maximum number of bytes to store each frame.

Restricting resolution changes to segment boundaries may not be acceptable. I will have to discuss this more with the users.

> We could reserve space at the start or end of the file and write the current frame reader state there after each frame is read.

That may be for the best. Created https://github.com/openmpf/openmpf/issues/166 to address this at a later time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by brosenberg42** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by jrobble** [comment]
Please update "Copyright 2016" to "Copyright 2017" in all of your class files.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-:-KxFDAzRYNyJdD7rcbFq:bsbimhb)*

**Comment by jrobble** [comment]
Actually, check the copyright in all of your files.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-:-KxFE4eHxnMT04V-3XOQ:b-61rse7)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[detection/api/CMakeLists.txt, line 33 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-KpFyR3NPQCzTuaciwFV:-KxJCD3KGqE4LOH5F8q6:b-79qay0) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/CMakeLists.txt#L33)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Just a friendly reminder that we should update this to 3.2 before this code lands.
</blockquote></details>

Now 3.3!

---

*[detection/api/include/streaming/MPFFrameStore.h, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-Kp25Rcp3Wql3PVyXg7s:-KxJCx09QgP6y5i6cNPg:b-k99q1d) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/6c83c5010ed8be91e1a0ebf30c5bf251b57d5cfe/detection/api/include/streaming/MPFFrameStore.h#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> The current frame storage approach would support changes in frame size where the frame size is smaller than the size of the original frame. It does not support frame sizes that are larger than the original frame size. Our current crop of detection components can't handle a change in frame size within a segment that is being processed, but we could certainly handle it on a segment boundary with no changes. Changing size from frame to frame would require more changes to the tracking logic itself.

I think it's reasonable if we require the user to specify the maximum frame size (width and height) when creating the job so we know the maximum number of bytes to store each frame.

Restricting resolution changes to segment boundaries may not be acceptable. I will have to discuss this more with the users.

> We could reserve space at the start or end of the file and write the current frame reader state there after each frame is read.

That may be for the best. Created https://github.com/openmpf/openmpf/issues/166 to address this at a later time.
</blockquote></details>

New information has come to light. Users will be providing separate SD and HD streams, so we don't need to be concerned with resolution changes.

Based on the above discussion, it seems that we should be storing the following pieces of state in the memory-mapped file (to support recovery) at a minimum:

- Current frame index
- Current segment index
- Current frame offset (if we're still writing sequentially)
- Flag to determine if we're still writing sequentially or processing messages in the frame release queue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5)*

**Comment by jrobble** [comment]
I think you can just close this PR since your last commit essentially nullifies all changes this PR would make to the develop branch.

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/5#-:-L-3GdL9EzGVqVDdTQuc:bxns215)*

**Comment by clnowacki** [comment]
Changes to this repo in this pull request have been removed.

**Pull request closed without merging**
