### PR TITLE
Revised streaming api

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/42)

### CODE REVIEW

**Comment by jrobble** [comment]
It all looks good. I'm thinking that it may be cleaner to define everything you added in a separate header file called MPFStreamingDetectionComponent.h.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42#-:-L23E3LR21WbwtAP_Gde:bkvwsg1)*

**Comment by clnowacki** [comment]
I agree, the only thing needing attention being the MPFDetectionError definition which is in this file. Since we are now creating a completely independent streaming component API, we should consider an independent set of errors as well, and define them in a new enum class that could be more easily extended. But if we did this, we would need to keep in mind the translation that needs to take place to return the error value in the protobufs.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42#-:-L25eYYaqQMowxhE3-pF:b-qk65hs)*

**Comment by clnowacki** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42)*

**Comment by clnowacki** [comment]
Reviewed 3 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42#-L2L6bknxbM--NtRNpXF:-L2L6bknxbM--NtRNpXG:buofojy) (no related file):*
Brian: Are you planning to add an exception class for the streaming components?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42)*

**Comment by brosenberg42** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42#-L2L6bknxbM--NtRNpXF:-L2L85V9g9XbRnjYQw6P:b5gwpg2) (no related file):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Brian: Are you planning to add an exception class for the streaming components?
</blockquote></details>

No, the streaming components will just throw anything that derives from std::exception. The component executor will catch this exception and re-throw a InternalComponentError. InternalComponentError is only used by the component executor so it will not be part of the component API. Basically it works like this:
```
bool StreamingComponentHandle::ProcessFrame(const cv::Mat &frame, int frame_number) {
    try {
        return loaded_component_->ProcessFrame(frame, frame_number);
    }
    catch (...) {
        WrapComponentException("ProcessFrame");
    }
}

std::vector<MPFVideoTrack> StreamingComponentHandle::EndSegment() {
    try {
        return loaded_component_->EndSegment();
    }
    catch (...) {
        WrapComponentException("EndSegment");
    }
}


void StreamingComponentHandle::WrapComponentException(const std::string &component_method) {
    try {
        throw;
    }
    catch (const std::exception &ex) {
        throw InternalComponentError(component_method, ex.what());
    }
    catch (...) {
        throw InternalComponentError(component_method);
    }

}
```
```
InternalComponentError::InternalComponentError(const std::string &method_name, const std::string &cause)
        : std::runtime_error(
            "The loaded component threw an exception while executing its \"" + method_name +"\" method: " + cause) {

}

InternalComponentError::InternalComponentError(const std::string &method_name)
        : runtime_error(
            "The loaded component threw an object that does not derive from std::exception while executing its \""
            + method_name + " method.") {
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42)*

**Comment by clnowacki** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42#-L2L6bknxbM--NtRNpXF:-L2LFXVlFVLh_T8woPtx:bz7xnac) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

No, the streaming components will just throw anything that derives from std::exception. The component executor will catch this exception and re-throw a InternalComponentError. InternalComponentError is only used by the component executor so it will not be part of the component API. Basically it works like this:
```
bool StreamingComponentHandle::ProcessFrame(const cv::Mat &frame, int frame_number) {
    try {
        return loaded_component_->ProcessFrame(frame, frame_number);
    }
    catch (...) {
        WrapComponentException("ProcessFrame");
    }
}

std::vector<MPFVideoTrack> StreamingComponentHandle::EndSegment() {
    try {
        return loaded_component_->EndSegment();
    }
    catch (...) {
        WrapComponentException("EndSegment");
    }
}


void StreamingComponentHandle::WrapComponentException(const std::string &component_method) {
    try {
        throw;
    }
    catch (const std::exception &ex) {
        throw InternalComponentError(component_method, ex.what());
    }
    catch (...) {
        throw InternalComponentError(component_method);
    }

}
```
```
InternalComponentError::InternalComponentError(const std::string &method_name, const std::string &cause)
        : std::runtime_error(
            "The loaded component threw an exception while executing its \"" + method_name +"\" method: " + cause) {

}

InternalComponentError::InternalComponentError(const std::string &method_name)
        : runtime_error(
            "The loaded component threw an object that does not derive from std::exception while executing its \""
            + method_name + " method.") {
}
```
</blockquote></details>

I see. Makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42)*

**Comment by clnowacki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42)*

**Comment by clnowacki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42#-:-L2LQL-KI-DQ2QRxSrlX:bnfp4nl)*

**Comment by jrobble** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/42)*

**Pull request merged**
