### PR TITLE
Make HelloWorld component return tracks in correct segment.

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/47)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/47)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[detection/examples/HelloWorldComponent/StreamingHelloWorld.cpp, line 76 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/47#-L44JYHkjGcRd_b6A11i:-L44JYHl3zgNIKPGjiaU:brm49v4) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/f9005d4b6fc0bf61d0f49cae7fbdf404e6823f09/detection/examples/HelloWorldComponent/StreamingHelloWorld.cpp#L76)):*
> ```cpp
>         segment_detections_.push_back(std::move(track));
>     }
>     return true;
> ```

This should only return true when generating the first track.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/47)*

**Comment by brosenberg42** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[detection/examples/HelloWorldComponent/StreamingHelloWorld.cpp, line 76 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/47#-L44JYHkjGcRd_b6A11i:-L47QRvxG3_WMX4doUoH:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/f9005d4b6fc0bf61d0f49cae7fbdf404e6823f09/detection/examples/HelloWorldComponent/StreamingHelloWorld.cpp#L76)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This should only return true when generating the first track.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/47)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/47)*

**Pull request merged**
