### PR TITLE
Add streaming support to HelloWorldComponent.

### PR DESCRIPTION
**Pull request by brosenberg42**
This is because Jenkins builds the sample components, not the test components.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/44)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/StreamingHelloWorld.cpp, line 34 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L33yJtUeSIpzCsCcmxK:-L33yJtVWDRhzfA1H7Ya:b3norqb) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/5ca06ea9d1c82fab88a6bb2a28334fe10066780e/detection/examples/HelloWorldComponent/StreamingHelloWorld.cpp#L34)):*
> ```cpp
> 
> 
> StreamingHelloWorld::StreamingHelloWorld(const MPFStreamingVideoJob &job)
> ```

This matches the streaming implementation of the test component in the openmpf repo. For consistency, the batch implementation of this component should be copied over to that repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by jrobble** [comment]
Reviewed 2 of 3 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/HelloWorld.h, line 36 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L34hU5MSMaLfHO0Gj0m:-L34hU5NlEzV4vhudX00:blttw5g) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/b183eda136f6b848cb0b6616a4711463e33bf988/detection/examples/HelloWorldComponent/HelloWorld.h#L36)):*
> ```objc
> 
> using namespace MPF;
> using namespace COMPONENT;
> ```

The other example components do `namespace MPF { namespace COMPONENT {` here. Isn't that  a bit cleaner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by brosenberg42** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/HelloWorld.h, line 36 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L34hU5MSMaLfHO0Gj0m:-L34txA2XN0yaqd7eGry:b-7bb9oe) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/b183eda136f6b848cb0b6616a4711463e33bf988/detection/examples/HelloWorldComponent/HelloWorld.h#L36)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The other example components do `namespace MPF { namespace COMPONENT {` here. Isn't that  a bit cleaner?
</blockquote></details>

I actually prefer that components are not in the MPF::COMPONENT namespace.  If a third party developer uses this as template they may believe that they should also put their component in the MPF::COMPONENT namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by jrobble** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/HelloWorld.h, line 36 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L34hU5MSMaLfHO0Gj0m:-L34zna2hM0689Z5o0P4:bxxx4gf) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/b183eda136f6b848cb0b6616a4711463e33bf988/detection/examples/HelloWorldComponent/HelloWorld.h#L36)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I actually prefer that components are not in the MPF::COMPONENT namespace.  If a third party developer uses this as template they may believe that they should also put their component in the MPF::COMPONENT namespace.
</blockquote></details>

That makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/sample_hello_world_detector.cpp, line 38 at r3](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L3CFwDHBfxsJlM171OF:-L3CFwDIwhJS0quyQWIU:b-8myyph) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/ff94cb13d5928c139af52dd6379304220e5b7d94/detection/examples/HelloWorldComponent/sample_hello_world_detector.cpp#L38)):*
Although we aren't using FRAME_INTERVAL anymore, I think it would be good to show how prop3 can be set on the command line since that is the one we're printing out.

Note that any changes made to the number and kind of command line arguments should be reflected in this line in the README:

> ./sample_hello_world_detector -v <video_file> 0 100 5

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/sample_hello_world_detector.cpp, line 38 at r3](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L3CFwDHBfxsJlM171OF:-L3Dhc4G6mjc-3n3ryhh:b-kcjc7q) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/ff94cb13d5928c139af52dd6379304220e5b7d94/detection/examples/HelloWorldComponent/sample_hello_world_detector.cpp#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Although we aren't using FRAME_INTERVAL anymore, I think it would be good to show how prop3 can be set on the command line since that is the one we're printing out.

Note that any changes made to the number and kind of command line arguments should be reflected in this line in the README:

> ./sample_hello_world_detector -v <video_file> 0 100 5


</blockquote></details>

I don't understand how that would be helpful. I think it would just confuse people. In general when there is a required argument, people are going to assume they have to provide a valid argument. This will make people waste time trying to figure out  what they are supposed to pass in. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[detection/examples/HelloWorldComponent/sample_hello_world_detector.cpp, line 38 at r3](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44#-L3CFwDHBfxsJlM171OF:-L3E0LQWHVIdc1CeeQux:b-p0j0oa) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/ff94cb13d5928c139af52dd6379304220e5b7d94/detection/examples/HelloWorldComponent/sample_hello_world_detector.cpp#L38)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't understand how that would be helpful. I think it would just confuse people. In general when there is a required argument, people are going to assume they have to provide a valid argument. This will make people waste time trying to figure out  what they are supposed to pass in. 
</blockquote></details>

Since this component doesn't do any real work, the parameters are pretty much placeholders. The URI doesn't have to be a valid. The time/frame parameters have to be numbers, but they don't need to correspond to anything. I think adding prop3 is a matter of preference. If you think it's confusing we don't need to add it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/44)*

**Pull request merged**
