### PR TITLE
Disable CAP_PROP_ORIENTATION_AUTO.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1501

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1504
- https://github.com/openmpf/openmpf-python-component-sdk/pull/60

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110)

### CODE REVIEW

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[detection/api/src/MPFVideoCapture.cpp, line 64 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110#-Myw165M7_JWTSwd6jx9:-Myw165M7_JWTSwd6jxA:bhge9v8) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/f0301e171656fa04190ccfefdb0ff2f3900cf863/detection/api/src/MPFVideoCapture.cpp#L64)):*
> ```cpp
> 
> 
>     MPFVideoCapture::MPFVideoCapture(const std::string videoPath)
> ```

By making this const, your are making the move below actually a copy. Moving from an object changes the original object, but in this case you made the original object const. In general you shouldn't use const with pass by value. When you use a const reference, you are telling the caller that you won't change the caller's object. When you use pass by value, the function gets a copy so the caller's object can't be changed regardless of whether or not the parameter is const. [This](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html) explains why pass by value is used here rather than pass by const ref.

If we consider code like:
```
MPFVideoCapture cap("path")
```
When this is declared as `MPFVideoCapture::MPFVideoCapture(std::string videoPath)` like before, it results in "path" being moved in to the `videoPath` parameter and then moved in to the `MPFVideoJob`. 

If it were declared as `MPFVideoCapture::MPFVideoCapture(const std::string &videoPath)`, no work needs to be done to assign "path" to the `videoPath` parameter, but to create the `MPFVideoJob`,  "path" would have to be copied.
___
*[detection/api/src/MPFVideoCapture.cpp, line 70 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110#-Myw5--6-cKrHmRPZCAK:-Myw5--6-cKrHmRPZCAL:b-cap1l6) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/f0301e171656fa04190ccfefdb0ff2f3900cf863/detection/api/src/MPFVideoCapture.cpp#L70)):*
> ```cpp
> 
> 
>     cv::VideoCapture MPFVideoCapture::GetCvVideoCapture(const std::string videoPath) {
> ```

This should be a const reference. We shouldn't use pass by value and move here because the `cv::VideoCapture` constructor takes the parameter by const reference.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[detection/api/src/MPFVideoCapture.cpp, line 64 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110#-Myw165M7_JWTSwd6jx9:-MyyldHh2LxkTRlwMi4A:b-bhzeej) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/f0301e171656fa04190ccfefdb0ff2f3900cf863/detection/api/src/MPFVideoCapture.cpp#L64)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

By making this const, your are making the move below actually a copy. Moving from an object changes the original object, but in this case you made the original object const. In general you shouldn't use const with pass by value. When you use a const reference, you are telling the caller that you won't change the caller's object. When you use pass by value, the function gets a copy so the caller's object can't be changed regardless of whether or not the parameter is const. [This](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html) explains why pass by value is used here rather than pass by const ref.

If we consider code like:
```
MPFVideoCapture cap("path")
```
When this is declared as `MPFVideoCapture::MPFVideoCapture(std::string videoPath)` like before, it results in "path" being moved in to the `videoPath` parameter and then moved in to the `MPFVideoJob`. 

If it were declared as `MPFVideoCapture::MPFVideoCapture(const std::string &videoPath)`, no work needs to be done to assign "path" to the `videoPath` parameter, but to create the `MPFVideoJob`,  "path" would have to be copied.
</blockquote></details>

Thanks for the thorough explanation. That all makes sense to me.
___
*[detection/api/src/MPFVideoCapture.cpp, line 70 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110#-Myw5--6-cKrHmRPZCAK:-MyymRz29jvFeImStOro:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/f0301e171656fa04190ccfefdb0ff2f3900cf863/detection/api/src/MPFVideoCapture.cpp#L70)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be a const reference. We shouldn't use pass by value and move here because the `cv::VideoCapture` constructor takes the parameter by const reference.
</blockquote></details>

Done.

**Review by brosenberg42 — COMMENTED** [review]
In the Python PR, you also changed MPFImageReader.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110#-:-Myw62n01-Yy4KdDovA-:b-lo46m4)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jrobble)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
