### PR TITLE
Add seek fallback functionality to MPFVideoCapture

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/16)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[detection/api/include/SeekStrategy.h, line 8 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB1wBU0MyIcC85RDL_:-KsB1wBU0MyIcC85RDLa:buj9q86) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/include/SeekStrategy.h#L8)):*
> ```objc
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2016 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update copyright year.

---

*[detection/api/include/SeekStrategy.h, line 12 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB22qowTydpqjPrX4v:-KsB22qowTydpqjPrX4w:buj9q86) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/include/SeekStrategy.h#L12)):*
> ```objc
> 
> /******************************************************************************
>  * Copyright 2016 The MITRE Corporation                                       *
> ```

Update copyright year.

---

*[detection/api/src/FrameSkipper.cpp, line 8 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB2O2_UK5qtm69crTD:-KsB2O2_UK5qtm69crTE:b-efijbs) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/FrameSkipper.cpp#L8)):*
> ```cpp
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2016 The MITRE Corporation. All Rights Reserved.                 *
> ```

This copyright should be 2017 in the code in the develop branch. Please make sure the header comments in other files get updated too.

---

*[detection/api/src/MPFVideoCapture.cpp, line 113 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB5hbmUNd1E9ayqoGE:-KsB5hbn1D8Plasj-ry5:b-oxrdpi) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L113)):*
> ```cpp
>         }
> 
>         while (seekStrategy_) {
> ```

This `while` initially confused me. Please leave a comment explaining that if the seek fails then we will fallback to a different `seekStrategy_`. When we're out of options, that will be a null pointer, in which case this function returns `false`.

---

*[detection/api/src/MPFVideoCapture.cpp, line 136 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB6RDQcgINqwQxpto7:-KsB6RDRg8-iYsmFWmEB:blyim64) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L136)):*
> ```cpp
>         }
> 
>         bool wasSet = SetPropertyInternal(VideoCaptureProperties::CAP_PROP_POS_FRAMES, 0);
> ```

Please leave a comment explaining the purpose of this line. It looks like a sanity test.

---

*[detection/api/src/MPFVideoCapture.cpp, line 187 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB7NFQc232IRM7gNJt:-KsB7NFRtsCYFtBZpU1k:b-2s4onh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L187)):*
> ```cpp
>             int segPosBeforeRead = frameSkipper_.OriginalToSegmentFramePosition(framePosition_ - 1);
>             int nextOriginalFrame = frameSkipper_.SegmentToOriginalFramePosition(segPosBeforeRead + 1);
>             UpdateOriginalFramePosition(nextOriginalFrame);
> ```

`UpdateOriginalFramePosition` can return false. Should we check that value and do something with it here?

---

*[detection/api/src/MPFVideoCapture.cpp, line 337 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB7Z56mSrJtei62gXU:-KsB7Z573DXCsO-TBG9b:b-2s4onh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L337)):*
> ```cpp
>         }
> 
>         UpdateOriginalFramePosition(initialFramePos);
> ```

`UpdateOriginalFramePosition` can return false. Should we check that value and do something with it here?

---

*[detection/api/src/SeekStrategy.cpp, line 8 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB2-7Bc8CV8vQqtegj:-KsB2-7C_Tnhfv4fLA1d:buj9q86) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L8)):*
> ```cpp
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2016 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update copyright year.

---

*[detection/api/src/SeekStrategy.cpp, line 12 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB210RZu7c-v2lyGRy:-KsB210SzOn8VRVf8IML:buj9q86) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L12)):*
> ```cpp
> 
> /******************************************************************************
>  * Copyright 2016 The MITRE Corporation                                       *
> ```

Update copyright year.

---

*[detection/api/src/SeekStrategy.cpp, line 56 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB8vEq-BJRbANIyCum:-KsB8vErDBZuJNjo-dAo:bpfgjwh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L56)):*
> ```cpp
>         }
>         else {
>             if (!cap.set(cv::VideoCaptureProperties::CAP_PROP_POS_FRAMES, 0)) {
> ```

Please leave a comment stating the purpose of this line. I assume it's because you want to iterate starting from the very beginning of the video.

---

*[detection/api/src/SeekStrategy.cpp, line 62 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB9XCL53P0oY_XUwx5:-KsB9XCMLCTvjEZwCcLC:b-rqqqv3) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L62)):*
> ```cpp
>         }
> 
>         int numGrabs = requestedPosition - start;
> ```

Let's name `numGrabs` something more generic to not confuse this with the `GrabSeek` strategy.

---

*[detection/api/src/SeekStrategy.cpp, line 85 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB4gw4r4ssle4AOyfg:-KsB4gw5SEhqQ2zRgh1y:b8dmkyb) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L85)):*
> ```cpp
>     SeekStrategy::CPtr GrabSeek::fallback() const {
>         std::cerr << "GrabSeek failed: falling back to ReadSeek" << std::endl;
>         return SeekStrategy::CPtr(new ReadSeek);
> ```

Have you ever seen a case where `grab()` didn't work but `read()` did?

---

*[detection/api/test/test_detection_api.cpp, line 601 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsBCTdsUtj3TRJNsl2T:-KsBCTdsUtj3TRJNsl2U:bv7u58h) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/test/test_detection_api.cpp#L601)):*
> ```cpp
>     ASSERT_TRUE(cap.read(frame)) << "Failed to read frame when seeking forward after backward seek";
>     ASSERT_EQ(GetFrameNumber(frame), 20) << "Incorrect frame read when seeking forward after backward seek";
>     framePosition++;
> ```

This `framePosition++` isn't necessary.

---

*[detection/api/test/test_detection_api.cpp, line 620 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsBBtFezqUfOKn-b8Pg:-KsBBtFezqUfOKn-b8Ph:b-wlnrd3) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/test/test_detection_api.cpp#L620)):*
> ```cpp
> }
> 
> //TEST(FrameSkipTest, CreateTestVideo) {
> ```

Please state which of the two test videos this is referring to. Specifically, it's frame_skip_test.avi, not the one with the frame issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by brosenberg42** [comment]
*[detection/api/src/SeekStrategy.cpp, line 85 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB4gw4r4ssle4AOyfg:-KsE_KRV1Cp7kTmXRxc4:b2nhky0) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L85)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Have you ever seen a case where `grab()` didn't work but `read()` did?
</blockquote></details>

No.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by brosenberg42** [comment]
*[detection/api/src/MPFVideoCapture.cpp, line 113 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB5hbmUNd1E9ayqoGE:-KsF8nKbF_3a97ck2PZc:b81c4yn) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L113)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This `while` initially confused me. Please leave a comment explaining that if the seek fails then we will fallback to a different `seekStrategy_`. When we're out of options, that will be a null pointer, in which case this function returns `false`.
</blockquote></details>

When I wrote this I was trying to decide between the implementation in the code and the one below. Do you think the implementation below is any easier to understand?
```
bool MPFVideoCapture::UpdateOriginalFramePosition(int requestedOriginalPosition) {
    if (framePosition_ == requestedOriginalPosition) {
        return true;
    }

    if (!seekStrategy_) {
        return false;
    }

    framePosition_ = seekStrategy_->ChangePosition(cvVideoCapture_, framePosition_, requestedOriginalPosition);
    if (framePosition_ == requestedOriginalPosition) {
        return true;
    }

    return SeekFallback() && UpdateOriginalFramePosition(requestedOriginalPosition);
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[detection/api/src/MPFVideoCapture.cpp, line 113 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB5hbmUNd1E9ayqoGE:-KsFCFprKe3S6yHopDXP:bspl8le) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L113)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

When I wrote this I was trying to decide between the implementation in the code and the one below. Do you think the implementation below is any easier to understand?
```
bool MPFVideoCapture::UpdateOriginalFramePosition(int requestedOriginalPosition) {
    if (framePosition_ == requestedOriginalPosition) {
        return true;
    }

    if (!seekStrategy_) {
        return false;
    }

    framePosition_ = seekStrategy_->ChangePosition(cvVideoCapture_, framePosition_, requestedOriginalPosition);
    if (framePosition_ == requestedOriginalPosition) {
        return true;
    }

    return SeekFallback() && UpdateOriginalFramePosition(requestedOriginalPosition);
}
```


</blockquote></details>

I think the latter is a bit easier to understand. The recursion makes sense to me.

---

*[detection/api/src/SeekStrategy.cpp, line 85 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB4gw4r4ssle4AOyfg:-KsFCMd0P0RVtt5VcKL_:b-bq5ph7) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L85)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

No.
</blockquote></details>

Okay. Just curious. I'm not saying any code changes are required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by jrobble** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by brosenberg42** [comment]
Review status: 2 of 10 files reviewed at latest revision, 13 unresolved discussions.

---

*[detection/api/include/SeekStrategy.h, line 8 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB1wBU0MyIcC85RDL_:-KsFj4L5cR4GRpK5tmT1:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/include/SeekStrategy.h#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update copyright year.
</blockquote></details>

Done.

---

*[detection/api/include/SeekStrategy.h, line 12 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB22qowTydpqjPrX4v:-KsFj4rnzyGnReB75ksO:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/include/SeekStrategy.h#L12)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update copyright year.
</blockquote></details>

Done.

---

*[detection/api/src/FrameSkipper.cpp, line 8 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB2O2_UK5qtm69crTD:-KsFj7_9YgEDM6t3gaQ8:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/FrameSkipper.cpp#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This copyright should be 2017 in the code in the develop branch. Please make sure the header comments in other files get updated too.
</blockquote></details>

Done.

---

*[detection/api/src/MPFVideoCapture.cpp, line 136 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB6RDQcgINqwQxpto7:-KsFj9hmxeQTeTueUTGd:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L136)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please leave a comment explaining the purpose of this line. It looks like a sanity test.
</blockquote></details>

Done.

---

*[detection/api/src/MPFVideoCapture.cpp, line 187 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB7NFQc232IRM7gNJt:-KsFjEHtE4gouGiWzdpS:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L187)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`UpdateOriginalFramePosition` can return false. Should we check that value and do something with it here?
</blockquote></details>

Done.

---

*[detection/api/src/MPFVideoCapture.cpp, line 337 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB7Z56mSrJtei62gXU:-KsFjFwPb0x4Ukig27Df:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/MPFVideoCapture.cpp#L337)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`UpdateOriginalFramePosition` can return false. Should we check that value and do something with it here?
</blockquote></details>

Done.

---

*[detection/api/src/SeekStrategy.cpp, line 8 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB2-7Bc8CV8vQqtegj:-KsFjH23jQCyaNe_Jle9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update copyright year.
</blockquote></details>

Done.

---

*[detection/api/src/SeekStrategy.cpp, line 12 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB210RZu7c-v2lyGRy:-KsFjHRwhL_dRfLBy8t2:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L12)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update copyright year.
</blockquote></details>

Done.

---

*[detection/api/src/SeekStrategy.cpp, line 56 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB8vEq-BJRbANIyCum:-KsFjM1sjyXAqpTqgTI-:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L56)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please leave a comment stating the purpose of this line. I assume it's because you want to iterate starting from the very beginning of the video.
</blockquote></details>

Done.

---

*[detection/api/src/SeekStrategy.cpp, line 62 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsB9XCL53P0oY_XUwx5:-KsFjNZTUQj83qM29-NC:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/src/SeekStrategy.cpp#L62)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's name `numGrabs` something more generic to not confuse this with the `GrabSeek` strategy.
</blockquote></details>

Done.

---

*[detection/api/test/test_detection_api.cpp, line 620 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsBBtFezqUfOKn-b8Pg:-KsFjRY7XWfPzY4x5hDo:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/test/test_detection_api.cpp#L620)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please state which of the two test videos this is referring to. Specifically, it's frame_skip_test.avi, not the one with the frame issues.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by brosenberg42** [comment]
Review status: 2 of 10 files reviewed at latest revision, 13 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 601 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16#-KsBCTdsUtj3TRJNsl2T:-KsFkNGxgvL0Fj7qVbSq:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/801cef9b6a9c1dc7bef5199806eb35e69cd70e26/detection/api/test/test_detection_api.cpp#L601)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This `framePosition++` isn't necessary.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Comment by jrobble** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/16)*

**Pull request merged**
