### PR TITLE
 Added support for generic detections.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/34)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[detection/api/include/MPFDetectionComponent.h, line 151 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyICYRaEkM2Ic_bHxTF:-KyICYRaEkM2Ic_bHxTG:bn1rl6b) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/MPFDetectionComponent.h#L151)):*
> ```objc
>         Properties detection_properties;
> 
>         MPFGenericTrack(float confidence = -1, const Properties &detection_properties = {})
> ```

Please make this constructor `explicit`. It is possible to invoke this constructor with one argument which means that this constructor defines an implicit conversion from float to MPFGenericTrack. 

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 34 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyHsT6zuDGjIIKUENWk:-KyHsT6zuDGjIIKUENWl:b-qvi0bv) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L34)):*
> ```objc
> #include <vector>
> 
> #include "MPFDetectionComponent.h"
> ```

Please add: `include/adapters/MPFGenericDetectionComponentAdapter.h` to `detection/api/CMakeLists.txt`at line 83 so that change detection works in IDEs.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 47 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyHtvgNS2o20oV8cfTj:-KyHtvgNS2o20oV8cfTk:btptr4v) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L47)):*
> ```objc
>             if (audio_job.has_feed_forward_track) {
>                 MPFGenericTrack generic_feed_forward_track(audio_job.feed_forward_track.confidence, audio_job.feed_forward_track.detection_properties);
>                 generic_job.feed_forward_track = generic_feed_forward_track;
> ```

`generic_job.has_feed_forward_track` will be false since you used the constructor without the feed forward parameter.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 47 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyIC7TlI_VicJGYfFsg:-KyIC7TlI_VicJGYfFsh:b3dqb7x) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L47)):*
> ```objc
>             if (audio_job.has_feed_forward_track) {
>                 MPFGenericTrack generic_feed_forward_track(audio_job.feed_forward_track.confidence, audio_job.feed_forward_track.detection_properties);
>                 generic_job.feed_forward_track = generic_feed_forward_track;
> ```

Combining these two lines in to one line will invoke the move assignment operator instead of the copy assignment operator that is being used:
`generic_job.feed_forward_track = MPFGenericTrack(audio_job.feed_forward_track.confidence, audio_job.feed_forward_track.detection_properties);`

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 59 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyHzZ0T46HQpj5mvo8S:-KyHzZ0T46HQpj5mvo8T:b-7xcdjk) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L59)):*
> ```objc
> 
>             // convert generic tracks to expected type
>             for (auto generic_track : generic_tracks) {
> ```

You should change this to `for (auto &generic_track : generic_tracks) {` to avoid creating copies of each track.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 66 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI-GemJixKoUBwXWI5:-KyI-GemJixKoUBwXWI6:b-jmri27) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L66)):*
> ```objc
>                 }
>                 audio_track.confidence = generic_track.confidence;
>                 audio_track.detection_properties = generic_track.detection_properties;
> ```

You should change this to: `audio_track.detection_properties = std::move(generic_track.detection_properties);` to avoid copying all the detection properties.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 67 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI-i0NiNT84Y2YGUZ2:-KyI-i0NiNT84Y2YGUZ3:bknzgch) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L67)):*
> ```objc
>                 audio_track.confidence = generic_track.confidence;
>                 audio_track.detection_properties = generic_track.detection_properties;
>                 audio_tracks.push_back(audio_track);
> ```

You should change this to `audio_tracks.push_back(std::move(audio_track));` to avoid copying all the detection properties.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 73 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI6finl4Ma0bskFoTf:-KyI6finl4Ma0bskFoTg:b-6hwcy0) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L73)):*
> ```objc
>         };
> 
>         MPFDetectionError GetDetections(const MPFImageJob &image_job, std::vector<MPFImageLocation> &locations) override {
> ```

The comments regarding `MPFDetectionError GetDetections(const MPFAudioJob &audio_job, std::vector<MPFAudioTrack> &audio_tracks)`  apply here as  well.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 111 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI7PSYv6Nyhu5g1pEY:-KyI7PSYv6Nyhu5g1pEZ:bjq2eym) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L111)):*
> ```objc
>             if (video_job.has_feed_forward_track) {
>                 MPFGenericTrack generic_feed_forward_track(video_job.feed_forward_track.confidence, video_job.feed_forward_track.detection_properties);
>                 generic_job.feed_forward_track = generic_feed_forward_track;
> ```

You need to set `generic_job.has_feed_forward_track = true`

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 123 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI7jxYdVK_fSKgaMD6:-KyI7jxYdVK_fSKgaMD7:b-egobis) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L123)):*
> ```objc
> 
>             // convert generic tracks to expected type
>             for (auto generic_track : generic_tracks) {
> ```

This should use a reference: `for (auto &generic_track : generic_tracks) {`

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 133 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI8WZRLizjiCghLM9s:-KyI8WZRLizjiCghLM9t:bd2vgv8) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L133)):*
> ```objc
> 
>                 // a video track needs at least one frame location
>                 video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, generic_track.detection_properties);
> ```

Here `generic_track.detection_properties` needs to be copied once since it gets added to both structs. The MPFImageLocation constructor copies the detection properties map no matter what. 

So this and the previous line can be changed to either:
```
 video_track.detection_properties = std::move(generic_track.detection_properties);
 video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, video_track.detection_properties);
```

or 

```
video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, generic_track.detection_properties);
video_track.detection_properties = std::move(generic_track.detection_properties);
```

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 135 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI886Upv6VpknCjNTl:-KyI886Upv6VpknCjNTm:b8u02s8) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L135)):*
> ```objc
>                 video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, generic_track.detection_properties);
> 
>                 video_tracks.push_back(video_track);
> ```

This should be `video_tracks.push_back(std::move(video_track));` to avoid unnecessary copy.

---

*[detection/examples/GenericComponent/GenericComponent.h, line 42 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyIDYnUs-By9CO26qUA:-KyIDYnUs-By9CO26qUB:badv05a) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/examples/GenericComponent/GenericComponent.h#L42)):*
> ```objc
> public:
> 
>     bool Init();
> ```

Each of these methods should be marked `override`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34)*

**Comment by brosenberg42** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 133 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI8WZRLizjiCghLM9s:-KyM6Bk04N4PyVfpop23:b-hjh1ws) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L133)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Here `generic_track.detection_properties` needs to be copied once since it gets added to both structs. The MPFImageLocation constructor copies the detection properties map no matter what. 

So this and the previous line can be changed to either:
```
 video_track.detection_properties = std::move(generic_track.detection_properties);
 video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, video_track.detection_properties);
```

or 

```
video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, generic_track.detection_properties);
video_track.detection_properties = std::move(generic_track.detection_properties);
```
</blockquote></details>

The line: `video_track.detection_properties = std::move(generic_track.detection_properties);` empties `generic_track.detection_properties`. In general, you should not use any objects after they have been moved from. Calling `std::move(obj)` is basically saying, I'm never going use obj again so you can perform any optimizations that modify obj in the process (generally it steals `obj`'s resources to avoid copying them).

The line `video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, generic_track.detection_properties);` copies `generic_track.detection_properties` which is now empty, instead it should copy from `video_track.detection_properties`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34)*

**Comment by jrobble** [comment]
Review status: 21 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 47 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyHtvgNS2o20oV8cfTj:-KyMGEVc9gHUkj2SFPMg:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L47)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`generic_job.has_feed_forward_track` will be false since you used the constructor without the feed forward parameter.
</blockquote></details>

Done.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 111 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI7PSYv6Nyhu5g1pEY:-KyMGFwDpULjOSyPhlzw:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L111)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You need to set `generic_job.has_feed_forward_track = true`
</blockquote></details>

Done.

---

*[detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h, line 133 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-KyI8WZRLizjiCghLM9s:-KyMH6qPJ9K5kPprbHSF:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/9ad3e7a9b48b8aa61bde954ebb19cf5db5ce8ae2/detection/api/include/adapters/MPFGenericDetectionComponentAdapter.h#L133)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The line: `video_track.detection_properties = std::move(generic_track.detection_properties);` empties `generic_track.detection_properties`. In general, you should not use any objects after they have been moved from. Calling `std::move(obj)` is basically saying, I'm never going use obj again so you can perform any optimizations that modify obj in the process (generally it steals `obj`'s resources to avoid copying them).

The line `video_track.frame_locations[0] = MPFImageLocation(0, 0, 0, 0, generic_track.confidence, generic_track.detection_properties);` copies `generic_track.detection_properties` which is now empty, instead it should copy from `video_track.detection_properties`. 

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/34#-:-KyMY6H4qnHhrcGLLkdX:bnfp4nl)*

**Pull request merged**
