### PR TITLE
added feed forward tracks to the detection jobs

### PR DESCRIPTION
**Pull request by clnowacki**
Added optional feed-forward location/track to the detection job structures.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/11)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[detection/api/include/MPFDetectionComponent.h, line 169 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-KqkA0trtcQD-vPlPuzf:-KqkA0trtcQD-vPlPuzg:btn1lvw) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L169)):*
> ```objc
>         const int start_frame;
>         const int stop_frame;
>         bool has_feed_forward_track = false;
> ```

Do we want a flag for this or is it acceptable to just check if feed_forward_track is null? The same kind of question applies to audio and image jobs.

@brosenberg42, do you have an opinion?

---

*[detection/api/include/MPFDetectionComponent.h, line 210 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-Kqk9o6Q9zkyAilXdxYy:-Kqk9o6Q9zkyAilXdxYz:bl6sd92) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L210)):*
> ```objc
>                 , has_feed_forward_location(false) {
>         }
>         MPFImageJob(const std::string &job_name,
> ```

Please add a blank line above this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[detection/api/include/MPFDetectionComponent.h, line 169 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-KqkA0trtcQD-vPlPuzf:-Kqx1tpEyByst0XukVyQ:b-y6lg8y) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L169)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we want a flag for this or is it acceptable to just check if feed_forward_track is null? The same kind of question applies to audio and image jobs.

@brosenberg42, do you have an opinion?
</blockquote></details>

The `feed_forward_track` field is not a pointer, so it can not be set to null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[detection/api/include/MPFDetectionComponent.h, line 169 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-KqkA0trtcQD-vPlPuzf:-Kqx5yiuQn1q-RTSd6X9:bj1i6zf) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L169)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The `feed_forward_track` field is not a pointer, so it can not be set to null.
</blockquote></details>

We could make it a pointer. That would enable us to use one constructor where `feed_forward_track` has a default parameter value of NULL. It will also allow us to do away with the `has_feed_forward_track` flag.

However, it seems that not using a pointer is a bit cleaner. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[detection/api/include/MPFDetectionComponent.h, line 169 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-KqkA0trtcQD-vPlPuzf:-Kqx9BzVau5dF4tsrL4O:b-r3dz2k) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L169)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We could make it a pointer. That would enable us to use one constructor where `feed_forward_track` has a default parameter value of NULL. It will also allow us to do away with the `has_feed_forward_track` flag.

However, it seems that not using a pointer is a bit cleaner. What do you think?
</blockquote></details>

I think the way Carol has it is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[detection/api/include/MPFDetectionComponent.h, line 169 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-KqkA0trtcQD-vPlPuzf:-Kqx9wTiD2xL_Eu66K_1:b-w6oogh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L169)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think the way Carol has it is fine.
</blockquote></details>

Ok, @clnowacki, please leave this as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[detection/api/include/MPFDetectionComponent.h, line 210 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-Kqk9o6Q9zkyAilXdxYy:-Kr1-p2WEXAr4P83y9xu:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/13054de3b4155adc662fddafe5c066567726ef7a/detection/api/include/MPFDetectionComponent.h#L210)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a blank line above this one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11)*

**Comment by jrobble** [comment]
@brosenberg42, it looks like you need to complete your Reviewable review.

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/11#-:-Kr5sz5jwJm2RPWT3fyi:bnfp4nl)*

**Pull request merged**
