### PR TITLE
Add ff region option

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/29)

### CODE REVIEW

**Comment by brosenberg42** [comment]
I am planning on adding system tests tomorrow.

**Comment by jrobble** [comment]
Please update the Caffe descriptor file:

FEED_FORWARD_TYPE:

> Applies to images and videos. The type of feed-forward behavior. Controls how this algorithm will make use of the tracks generated in the previous pipeline stage. If this algorithm is used in the first pipeline stage then this property has no effect. Instead, the default segmenting behavior is used, where tracks from the previous stage are used to generate segments based on the TARGET_SEGMENT_LENGTH and MIN_SEGMENT_LENGTH properties. Can be set to “NONE”, “FRAME”, “SUPERSET_REGION”, or “REGION”. If set to “NONE”, the default segmenting behavior is used. If set to “FRAME”, “SUPERSET_REGION”, or “REGION” then the segment length properties are ignored and instead this algorithm will process one segment per track generated in the previous stage. If set to “FRAME”, then this algorithm will ignore the regions associated with previous detections and instead process the entire frame associated with each of those detections. If set to “SUPERSET_REGION”, then this algorithm will generate a superset region for each of the previous tracks – a bounding box of constant size and position that encloses all of the track’s detection regions. This algorithm will only process the data within the superset region. If set to “REGION”, then this algorithm will use the regions associated with previous detections, which may vary in size and position from frame to frame.


FEED_FORWARD_TOP_CONFIDENCE_COUNT

> Only applies if FEED_FORWARD_TYPE is set to a value other than “NONE”. If set to a value <= 0, then for each track generated in the previous pipeline stage, this algorithm will process the frame associated with each detection in that track, ignoring frames that don’t have detections. If FEED_FORWARD_TYPE is set to “FRAME”, then the entire frame is processed. If FEED_FORWARD_TYPE is set to “SUPERSET_REGION”, then only the superset region for those frames is processed. If FEED_FORWARD_TYPE is set to “REGION”, then the specific detection region for each frame is processed. If this property is set to “1” then only the exemplar frame for each of the previous tracks is processed. If this property is set to a value > 1, say 5, then each of the detections in the previous track are sorted by confidence and this algorithm will only process the frames associated with the top 5 detections with the highest confidence. For detections with the same confidence values, it will select those with a lower frame index. If the track contains less than 5 detections, then all of the available detections are used. In practice, setting this property to a value > 1 has no effect on image and audio jobs because each track only contains one detection.

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[detection/api/include/frame_transformers/BaseDecoratedTransformer.h, line 57 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-KwapwFj3-4oosTAvr5Z:-KwapwFko07OhNBKHMl_:b2d40fl) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d0351de06580efa34630cd4a716cc0d2b4a94b6c/detection/api/include/frame_transformers/BaseDecoratedTransformer.h#L57)):*
> ```objc
>          * @param frame[in,out] Frame to transform.
>          */
>         void TransformFrame(cv::Mat &frame, int frameIndex) override;
> ```

Please update the function comments with the new param.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-:-Kwaszr4B55EHJFIDbD4:bz1ypyg)*

**Comment by jrobble** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/src/frame_transformers/FrameCropper.cpp, line 65 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-Kwc5Mj8NUln9KbAcxKk:-Kwc5Mj9OuXY8R_uVinq:b-fcjd64) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d0351de06580efa34630cd4a716cc0d2b4a94b6c/detection/api/src/frame_transformers/FrameCropper.cpp#L65)):*
> ```cpp
> 
>     }
>     cv::Rect SearchRegionFrameCropper::GetIntersectingRegion(const cv::Rect &regionOfInterest, int frameIndex) const {
> ```

Add a blank line above this function.

---

*[detection/api/test/test_detection_api.cpp, line 964 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-Kwc62t1AbvlJhXiyTTO:-Kwc62t1AbvlJhXiyTTP:b-3pcb7f) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d0351de06580efa34630cd4a716cc0d2b4a94b6c/detection/api/test/test_detection_api.cpp#L964)):*
> ```cpp
>         const auto &outLocation = outPair.second;
>         const auto &ffLocation = feedForwardTrack.frame_locations.at(outPair.first);
>         ASSERT_EQ(outLocation.x_left_upper, ffLocation.x_left_upper);
> ```

Please add a test where the detection is offset within the FF region.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29)*

**Comment by brosenberg42** [comment]
Review status: 13 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[detection/api/include/frame_transformers/BaseDecoratedTransformer.h, line 57 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-KwapwFj3-4oosTAvr5Z:-Kwf99mZx1Sjzolctn6y:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d0351de06580efa34630cd4a716cc0d2b4a94b6c/detection/api/include/frame_transformers/BaseDecoratedTransformer.h#L57)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the function comments with the new param.
</blockquote></details>

Done.

---

*[detection/api/src/frame_transformers/FrameCropper.cpp, line 65 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-Kwc5Mj8NUln9KbAcxKk:-Kwf9GdNiDhbpUkuUwEY:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d0351de06580efa34630cd4a716cc0d2b4a94b6c/detection/api/src/frame_transformers/FrameCropper.cpp#L65)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a blank line above this function.
</blockquote></details>

Done.

---

*[detection/api/test/test_detection_api.cpp, line 964 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29#-Kwc62t1AbvlJhXiyTTO:-Kwf98Bcd_L0oYGC9QOm:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/d0351de06580efa34630cd4a716cc0d2b4a94b6c/detection/api/test/test_detection_api.cpp#L964)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a test where the detection is offset within the FF region.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/29)*

**Pull request merged**
