### PR TITLE
Add MPFAsyncVideoCapture

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[detection/api/include/MPFAsyncVideoCapture.h, line 8 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTaxvvDCeYJCzReTkbr:-MTaxvvDCeYJCzReTkbs:b-9hae34) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/include/MPFAsyncVideoCapture.h#L8)):*
> ```objc
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2020 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update copyrights.
___
*[detection/api/src/IntervalFrameFilter.cpp, line 88 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTb3B1R12VRF_WoY8bE:-MTb3B1S8__Ra5gaixYL:b4izhqf) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/src/IntervalFrameFilter.cpp#L88)):*
> ```cpp
> 
>     int IntervalFrameFilter::GetStopFrame(const MPFVideoJob &job, int originalFrameCount) {
>         if (job.stop_frame >= 0 && job.stop_frame < originalFrameCount) {
> ```

This makes sense, but I'm wondering if you encountered a situation where the stop frame was 0, and if so, what was it?
___
*[detection/api/src/MPFAsyncVideoCapture.cpp, line 151 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTbAakdCqzqDgsUVgf1:-MTbAake9Ksqs9n5BNi2:bf18vuk) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/src/MPFAsyncVideoCapture.cpp#L151)):*
> ```cpp
> 
>     void MPFAsyncVideoCapture::ReverseTransform(MPFVideoTrack &videoTrack) const {
>         return reverseTransformer_(videoTrack);
> ```

Why `return` here?
___
*[detection/api/src/MPFVideoCapture.cpp, line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTauj5jDLSGKTNMOhST:-MTauj5kAcOMbmb9XaLN:blkxfos) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/src/MPFVideoCapture.cpp#L27)):*
> ```cpp
>  ******************************************************************************/
> 
> #include <algorithm>
> ```

CLion says `#include <algorithm>` is not used.
___
*[detection/api/test/test_detection_api.cpp, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTbB5E27rWYcWo0ohNz:-MTbB5E27rWYcWo0ohO-:b-azzpwg) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/test/test_detection_api.cpp#L34)):*
> ```cpp
> #include <gtest/gtest.h>
> 
> #include <opencv2/video.hpp>
> ```

CLion says `#include <opencv2/video.hpp>` is not used.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100)* status: 18 of 23 files reviewed, 5 unresolved discussions (waiting on @jrobble)

___
*[detection/api/include/MPFAsyncVideoCapture.h, line 8 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTaxvvDCeYJCzReTkbr:-MTfBJSe0MmqRNNOyGoj:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/include/MPFAsyncVideoCapture.h#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update copyrights.
</blockquote></details>

Done.
___
*[detection/api/src/IntervalFrameFilter.cpp, line 88 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTb3B1R12VRF_WoY8bE:-MTbIqLuBp138-aLFWGz:b-hwdmx3) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/src/IntervalFrameFilter.cpp#L88)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This makes sense, but I'm wondering if you encountered a situation where the stop frame was 0, and if so, what was it?
</blockquote></details>

It was when I was developing a unit test, not a real runtime situation.
___
*[detection/api/src/MPFAsyncVideoCapture.cpp, line 151 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTbAakdCqzqDgsUVgf1:-MTfBPr7BvWPTOmbup6l:b-e1m3mp) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/src/MPFAsyncVideoCapture.cpp#L151)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why `return` here?
</blockquote></details>

It shouldn't be there.
___
*[detection/api/src/MPFVideoCapture.cpp, line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTauj5jDLSGKTNMOhST:-MTbJVdE3D6njBYrETmb:b-g44zi9) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/src/MPFVideoCapture.cpp#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

CLion says `#include <algorithm>` is not used.
</blockquote></details>

CLion is wrong. `std::max` and `std::min` are from `<algorithm>`
___
*[detection/api/test/test_detection_api.cpp, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTbB5E27rWYcWo0ohNz:-MTfAriD3lI5W2xHINoU:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/test/test_detection_api.cpp#L34)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

CLion says `#include <opencv2/video.hpp>` is not used.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[detection/api/include/MPFAsyncVideoCapture.h, line 8 at r1](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100#-MTaxvvDCeYJCzReTkbr:-MTlicqY8rVKuZAW0aFx:b-5wd2j0) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/04a7159b54808599d25991d41133f6d5c65205af/detection/api/include/MPFAsyncVideoCapture.h#L8)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are still "Copyright 2020" in this branch, but I assume they will all be updated when you merge with develop. Please double-check.

**Review by jrobble — APPROVED** [review]
> Reviewed 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/100)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
