### PR TITLE
Add FeedForwardFrameSkipper

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-cpp-component-sdk/18)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 11 of 14 files at r1, 3 of 3 files at r2.
Review status: 13 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[detection/api/include/FeedForwardFrameSkipper.h, line 41 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseVq87o2TKsd5Qzd-w:-KseVq87o2TKsd5Qzd-x:bfzve2y) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/include/FeedForwardFrameSkipper.h#L41)):*
> ```objc
>     class FeedForwardFrameSkipper : public FrameSkipper {
>     public:
>         explicit FeedForwardFrameSkipper(const MPFVideoTrack &feedForwardTrack);
> ```

Why is this `explicit`?

---

*[detection/api/include/IntervalFrameSkipper.h, line 41 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseV413ASVDTOj9RuPR:-KseV414nLXwBZKD-OP5:b-jvw2xq) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/include/IntervalFrameSkipper.h#L41)):*
> ```objc
>      * and stop frames. Additionally many components support a FRAME_INTERVAL property.
>      * These values tell components to only process certain frames in the video. Instead of having components
>      * figure out which frames process and which frames to skip, this class performs the calculations necessary
> ```

Please add "to" here: 

"which frames to process"

---

*[detection/api/include/MPFVideoCapture.h, line 37 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse07b3mhK-DgoF2JZ-:-Kse07b3mhK-DgoF2JZ0:b-aavg44) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/include/MPFVideoCapture.h#L37)):*
> ```objc
> #include "MPFDetectionComponent.h"
> #include "frame_transformers/IFrameTransformer.h"
> #include "IntervalFrameSkipper.h"
> ```

Do you need to include IntervalFrameSkipper here? I don't see it used in this .h file.

---

*[detection/api/src/FeedForwardFrameSkipper.cpp, line 44 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseXf10YlWZiH32Ar8Z:-KseXf11WQFHOxrg59Ow:bkwzngh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/FeedForwardFrameSkipper.cpp#L44)):*
> ```cpp
>         framesInTrack.reserve(track.frame_locations.size());
> 
>         for (const auto &frameLocPair : track.frame_locations) {
> ```

It seems that you're assuming that the track will only contain the top detections that this job cares about. 

Thus, when the WFM gets a track from a previous stage, it will need to remove the detections from that track that aren't part of the top N. Then, when generating a sub-job, the WFM will need to ensure that the track fed to the sub-job does not contain detections that are outside of the sub-job start and stop frames (segment range). Is that correct?

Do we do any kind of sanity checking on the MPFVideoJob start and stop frames relative to the indexes of the frames in the feed-forward track?

Initially, my thought is that the WFM would send each sub-job the same feed-forward track information, and then the service processing that sub-job would only look at frames within the specified start and stop frames. However, it shouldn't be hard for the WFM to customize the feed-forward track for each sub-job, so I'm fine with this approach; but I do think we should do a sanity check on the range. Specifically, the feed-forward track for this sub-job should not contain a detection that corresponds to a frame outside of the range.

CCing @dpierce17.

---

*[detection/api/src/MPFVideoCapture.cpp, line 66 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Ksebo4H99tmVOX_sJYU:-Ksebo4H99tmVOX_sJYV:bv6sams) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/MPFVideoCapture.cpp#L66)):*
> ```cpp
>             return FrameSkipper::GetNoOpSkipper(frameCount);
>         }
>         if (job.has_feed_forward_track) {
> ```

I see that you're checking for the existence of a feed-forward track here, so even if the FEED_FORWARD_TYPE is specified for the sub-jobs corresponding to the first stage in the pipeline, then MPFVideoCapture will do the right thing and just ignore them, right?

---

*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 84 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse1un83rUfm65MlaEs:-Kse1un9j2qasv2A-Bu2:b-cubr97) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L84)):*
> ```cpp
> 
> 
>         cv::Rect GetFeedForwardRegion(const std::map<int, MPFImageLocation> &trackLocations) {
> ```

We should drop a comment about what we're doing here. Specifically, what the superset region is and why we're using it.

---

*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 154 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse2LWtKEOyGnqA--y9:-Kse2LWtKEOyGnqA--yA:byiaaue) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L154)):*
> ```cpp
> 
>             cv::Rect regionOfInterest;
>             if (FeedForwardCroppingIsEnabled(job.job_properties)) {
> ```

If the search region is also specified let's print a warning stating that it will be ignored in favor of the feed forward region.

---

*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 158 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse2e3nKPmw5ucXlZmN:-Kse2e3nKPmw5ucXlZmO:b1y6v8r) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L158)):*
> ```cpp
>             }
>             else if (SearchRegionCroppingIsEnabled(job.job_properties)) {
>                 regionOfInterest = GetSearchRegion(job.job_properties, inputVideoSize);
> ```

It appears that if FEED_FORWARD_TYPE == "FRAME" then the user can specify a search region. I haven't thought about that combination of properties, but it appears that we support it. Can we write a simple test for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by jrobble** [comment]
Review status: 13 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-KseiCsd4SsgyTtcQBTY:b8mbenv) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
I see that you changed the parameter order for `ASSERT_EQ`. According to [this](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md):

> Historical note: Before February 2016 *_EQ had a convention of calling it as ASSERT_EQ(expected, actual), so lots of existing code uses this order. Now *_EQ treats both parameters in the same way.

I have gtest version 1.7.0 on my dev VM. According to [GitHub](https://github.com/google/googletest/tree/release-1.7.0), the last commit was Sept. 2013. If we go off that version, we should be following the old convention. Are you using the new version, 1.8.0? 

We don't provide instructions on how to install gtest at all in the Build Guide, so technically we don't have a standard version, just what people have on their dev VMs. My dev VM is probably older than yours, so you may have a more modern version of gtest than me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by brosenberg42** [comment]
Review status: 9 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[detection/api/include/FeedForwardFrameSkipper.h, line 41 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseVq87o2TKsd5Qzd-w:-Ksi3VPtxykMidaAQ3Yu:bggqlqd) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/include/FeedForwardFrameSkipper.h#L41)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why is this `explicit`?
</blockquote></details>

It is explicit so that it cannot be used as a converting constructor to implicitly convert MPFVideoTrack objects to FeedForwardFrameSkipper objects.

---

*[detection/api/include/IntervalFrameSkipper.h, line 41 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseV413ASVDTOj9RuPR:-KsiUhcptjvnhTIhQ5TB:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/include/IntervalFrameSkipper.h#L41)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add "to" here: 

"which frames to process"
</blockquote></details>

Done.

---

*[detection/api/include/MPFVideoCapture.h, line 37 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse07b3mhK-DgoF2JZ-:-KsiUkDWmBilYr70v6ej:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/include/MPFVideoCapture.h#L37)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you need to include IntervalFrameSkipper here? I don't see it used in this .h file.
</blockquote></details>

Done.

---

*[detection/api/src/FeedForwardFrameSkipper.cpp, line 44 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseXf10YlWZiH32Ar8Z:-KsiP6SdV4H811wn0iTC:btp6ywh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/FeedForwardFrameSkipper.cpp#L44)):*
> It seems that you're assuming that the track will only contain the top detections that this job cares about.

In https://github.com/openmpf/openmpf/issues/176#issuecomment-322281770 you say: 
> "The WFM will be responsible for generating segments based on the value of FEED_FORWARD_TOP_CONFIDENCE_COUNT.


> Do we do any kind of sanity checking on the MPFVideoJob start and stop frames relative to the indexes of the frames in the feed-forward track?

Are you asking me to discard detections outside of start frame and stop frame?  

---

*[detection/api/src/MPFVideoCapture.cpp, line 66 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Ksebo4H99tmVOX_sJYU:-KsiOLplRI-YMljZFELr:b25zp0n) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/MPFVideoCapture.cpp#L66)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I see that you're checking for the existence of a feed-forward track here, so even if the FEED_FORWARD_TYPE is specified for the sub-jobs corresponding to the first stage in the pipeline, then MPFVideoCapture will do the right thing and just ignore them, right?
</blockquote></details>

No, GetFeedForwardRegion() in FrameTransformerFactory will throw an exception.

---

*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 84 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse1un83rUfm65MlaEs:-KsiUmfDZXGZcrCxBygH:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L84)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We should drop a comment about what we're doing here. Specifically, what the superset region is and why we're using it.
</blockquote></details>

Done.

---

*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 154 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse2LWtKEOyGnqA--y9:-KsiUpBeZDVmnB4UOGMG:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L154)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If the search region is also specified let's print a warning stating that it will be ignored in favor of the feed forward region.
</blockquote></details>

Done.

---

*[detection/api/src/frame_transformers/FrameTransformerFactory.cpp, line 158 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-Kse2e3nKPmw5ucXlZmN:-KsiUy0h36v2AJmNt3LX:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/frame_transformers/FrameTransformerFactory.cpp#L158)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It appears that if FEED_FORWARD_TYPE == "FRAME" then the user can specify a search region. I haven't thought about that combination of properties, but it appears that we support it. Can we write a simple test for it?
</blockquote></details>

Done.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-Ksi2HkoPAqNZ7bE91Ti:bwwrhyr) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I see that you changed the parameter order for `ASSERT_EQ`. According to [this](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md):

> Historical note: Before February 2016 *_EQ had a convention of calling it as ASSERT_EQ(expected, actual), so lots of existing code uses this order. Now *_EQ treats both parameters in the same way.

I have gtest version 1.7.0 on my dev VM. According to [GitHub](https://github.com/google/googletest/tree/release-1.7.0), the last commit was Sept. 2013. If we go off that version, we should be following the old convention. Are you using the new version, 1.8.0? 

We don't provide instructions on how to install gtest at all in the Build Guide, so technically we don't have a standard version, just what people have on their dev VMs. My dev VM is probably older than yours, so you may have a more modern version of gtest than me.
</blockquote></details>

I don't know how to check the version. I changed the order so that the failure messages made sense.
These are the two options:
```
Failure
      Expected: 6
To be equal to: myFunction()
      Which is: 5
```
or
```
Failure
      Expected: myFunction()
      Which is: 5
To be equal to: 6
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by jrobble** [comment]
Reviewed 1 of 14 files at r1.
Review status: 9 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 595 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsinJMSqWaHk7cCbrl4:-KsinJMUbdneE74hPlQF:brqfjjf) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L595)):*
> ```cpp
>     ASSERT_TRUE(cap.GetInitializationFramesIfAvailable(100).empty());
> 
>     cv::Size expectedSize(9, 11);
> ```

Please leave a comment explaining how you came up with 9 and 11.

---

*[detection/api/test/test_detection_api.cpp, line 612 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsinoqRddKRS1YqokHQ:-KsinoqRddKRS1YqokHR:b23izf5) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L612)):*
> ```cpp
> 
> 
>     MPFVideoTrack detection(0, 6);
> ```

Instead of calling this `detection`, let's call it `track`. A track contains multiple detections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-KsiqYdNBIZEWgg0abP-:bwdaugz) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
Try this:

`head -1 /apps/source/googletest/googletest/CHANGES`

For me that shows:

> Changes for 1.7.0:

Which of the two options you presented above seems more correct to you?

---

*[detection/api/test/test_detection_api.cpp, line 655 at r3](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsirPWJR7pjDgJFqc21:-KsirPWJR7pjDgJFqc22:bmd1gud) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/3a59c367e1396f3ad24d59ff6bbd46ec77851f2d/detection/api/test/test_detection_api.cpp#L655)):*
> ```cpp
> 
> 
> }
> ```

Looks good. We should add some tests to ensure that we're during the reverse transforms correctly for the following cases:

- No feed forward, no search region provided
- No feed forward, search region provided
- Feed forward, no search region provided
- Feed forward, search region provided

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[detection/api/src/FeedForwardFrameSkipper.cpp, line 44 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseXf10YlWZiH32Ar8Z:-KsizV2ThAkpVNqsLqbL:b-jstcyh) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/FeedForwardFrameSkipper.cpp#L44)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

> It seems that you're assuming that the track will only contain the top detections that this job cares about.

In https://github.com/openmpf/openmpf/issues/176#issuecomment-322281770 you say: 
> "The WFM will be responsible for generating segments based on the value of FEED_FORWARD_TOP_CONFIDENCE_COUNT.


> Do we do any kind of sanity checking on the MPFVideoJob start and stop frames relative to the indexes of the frames in the feed-forward track?

Are you asking me to discard detections outside of start frame and stop frame?  
</blockquote></details>

Yes, I think it makes sense to discard detections outside the start and stop frame range. If you need to do that, log an error message. The WFM should ensure that you don't need to do that, but you should do it just in case. 

Also, let's say the feed forward track has frames [0, 2, 4, 6, 8], the start frame for the job is 0, and the stop frame for the job is 9. Frame 9 isn't in the feed forward track, so you should probably log an error message.

Generally speaking, the job start frame should correspond to the first detection in the feed forward track, and the job stop frame should correspond to the last frame in the feed forward track. If that's not the case, then an error should be logged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[detection/api/src/FeedForwardFrameSkipper.cpp, line 44 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseXf10YlWZiH32Ar8Z:-Ksn2KYd6jmmJ5RLR-H1:bzcj2wu) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/FeedForwardFrameSkipper.cpp#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Yes, I think it makes sense to discard detections outside the start and stop frame range. If you need to do that, log an error message. The WFM should ensure that you don't need to do that, but you should do it just in case. 

Also, let's say the feed forward track has frames [0, 2, 4, 6, 8], the start frame for the job is 0, and the stop frame for the job is 9. Frame 9 isn't in the feed forward track, so you should probably log an error message.

Generally speaking, the job start frame should correspond to the first detection in the feed forward track, and the job stop frame should correspond to the last frame in the feed forward track. If that's not the case, then an error should be logged.
</blockquote></details>

I really think start and stop frame should be ignored when there is a feed forward track. There are two conflicting sets of parameters. I don't think we should combine the conflicting parameters. I think we should choose one set of parameters to use and ignore the others. When both a feed forward region and a search region are provided we don't combine the two regions.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-Ksiy95CZ3wr4ltxIt1t:b-dfj56h) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Try this:

`head -1 /apps/source/googletest/googletest/CHANGES`

For me that shows:

> Changes for 1.7.0:

Which of the two options you presented above seems more correct to you?

</blockquote></details>

```
Failure
      Expected: myFunction()
      Which is: 5
To be equal to: 6
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by brosenberg42** [comment]
Review status: 13 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 595 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsinJMSqWaHk7cCbrl4:-KsnIyEk5ERuCa48kjka:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L595)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please leave a comment explaining how you came up with 9 and 11.
</blockquote></details>

Done.

---

*[detection/api/test/test_detection_api.cpp, line 612 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsinoqRddKRS1YqokHQ:-KsnIu4dpM0f4g1TPcbx:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L612)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of calling this `detection`, let's call it `track`. A track contains multiple detections.
</blockquote></details>

Done.

---

*[detection/api/test/test_detection_api.cpp, line 655 at r3](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsirPWJR7pjDgJFqc21:-KsnIwX1AiDW_bACLeY6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/3a59c367e1396f3ad24d59ff6bbd46ec77851f2d/detection/api/test/test_detection_api.cpp#L655)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Looks good. We should add some tests to ensure that we're during the reverse transforms correctly for the following cases:

- No feed forward, no search region provided
- No feed forward, search region provided
- Feed forward, no search region provided
- Feed forward, search region provided
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by brosenberg42** [comment]
Review status: 13 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 655 at r3](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KsirPWJR7pjDgJFqc21:-Ksnld8FBcYgAvejGWpH:bpy1g57) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/3a59c367e1396f3ad24d59ff6bbd46ec77851f2d/detection/api/test/test_detection_api.cpp#L655)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The cases you mentioned are tested in these tests:
- NoFeedForwardNoSearchRegion
- NoFeedForwardWithSearchRegion
- CanHandleFeedForwardTrack
- CanUseSearchRegionWithFeedForwardFrameType

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[detection/api/src/FeedForwardFrameSkipper.cpp, line 44 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseXf10YlWZiH32Ar8Z:-Ksq5iM_GfDVTPGIJaqL:bqb8dso) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/FeedForwardFrameSkipper.cpp#L44)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I really think start and stop frame should be ignored when there is a feed forward track. There are two conflicting sets of parameters. I don't think we should combine the conflicting parameters. I think we should choose one set of parameters to use and ignore the others. When both a feed forward region and a search region are provided we don't combine the two regions.
</blockquote></details>

I agree that it makes sense to go with one set of parameters, but I also I think we should log an error and continue on if they conflict - like what we do when both a feed forward region and a search region are provided.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-Ksq4D66GCTkO1Fczz8i:b4rawp2) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

```
Failure
      Expected: myFunction()
      Which is: 5
To be equal to: 6
```
</blockquote></details>

Yeah, I agree. That seems more correct.

Does this command return anything for you?

`head -1 /apps/source/googletest/googletest/CHANGES`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-KssqtQjDzEIN3nA3r0q:b-7eq51n) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Yeah, I agree. That seems more correct.

Does this command return anything for you?

`head -1 /apps/source/googletest/googletest/CHANGES`
</blockquote></details>

That command does not accurately reflect the version of gtest. Even on master (https://github.com/google/googletest/blob/master/googletest/CHANGES) it says "Changes for 1.7.0:"
Mine also says "Changes for 1.7.0:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by brosenberg42** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[detection/api/src/FeedForwardFrameSkipper.cpp, line 44 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseXf10YlWZiH32Ar8Z:-Kst1VQyv3zZFfBAIkxQ:b2r9ek6) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/src/FeedForwardFrameSkipper.cpp#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I agree that it makes sense to go with one set of parameters, but I also I think we should log an error and continue on if they conflict - like what we do when both a feed forward region and a search region are provided.
</blockquote></details>

Done.
Added check in `MPFVideoCapture::GetFrameSkipper` since that is where it already checks `has_feed_forward_track`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[detection/api/test/test_detection_api.cpp, line 87 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18#-KseiCsd4SsgyTtcQBTX:-Kst09d1OnpeAIKcI6e6:b42y6xs) ([raw file](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/20e5da95612e9a956ef792f19bc5ecdeaabbad78/detection/api/test/test_detection_api.cpp#L87)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That command does not accurately reflect the version of gtest. Even on master (https://github.com/google/googletest/blob/master/googletest/CHANGES) it says "Changes for 1.7.0:"
Mine also says "Changes for 1.7.0:"
</blockquote></details>

Hmm, [this 1.8.0 file](https://github.com/google/googletest/blob/release-1.8.0/googletest/configure.ac) shows:

```
AC_INIT([Google C++ Testing Framework],
        [1.7.0],
        [googletestframework@googlegroups.com],
        [gtest])
```

Confusing. Oh well, let's not worry about this. I'm really fine with the output either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-cpp-component-sdk/18)*

**Pull request merged**
